name: Sync Conf To Client

on:
  push:
    paths:
      - '**.conf'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Checkout
        uses: actions/checkout@master
        with:
           token: ${{ secrets.GITHUB_TOKEN  }}

      # - name: Copy file to the client 
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.MACHINE_IP }}
      #     username: ${{ secrets.USERNAME }}
      #     port: ${{ secrets.PORT }}
      #     overwrite: true
      #     key: ${{ secrets.SSH_KEY }}
      #     source: "./accelerated-domains.china.domain.smartdns.conf,./gfwlist.domain.smartdns.conf"
      #     target: ${{ secrets.TARGET }}
          
      # - name: Restart smartdns
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.MACHINE_IP }}
      #     username: ${{ secrets.USERNAME }}
      #     port: ${{ secrets.PORT }}
      #     key: ${{ secrets.SSH_KEY }}
      #     script: docker restart smartdns

      - name: Add global nameserver
        run: sed '1i\h3://dns.cloudflare.com/dns-query\nh3://dns.google/dns-query' ./accelerated-domains.china.adguardhome.conf > ./dns.conf

      - name: Copy file to the server 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          overwrite: true
          key: ${{ secrets.SSH_KEY2 }}
          source: "./dns.conf"
          target: ${{ secrets.TARGET2 }}
          
      - name: Restart adguardhome
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_KEY2 }}
          script: docker restart adguardhome
  
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 2
